services:
  - type: web
    name: guild-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_TOKEN
        prompt: true